### ISSUE TITLE
Thermostat

### ISSUE THREAD

**Issue by luxus** [maddox/homebridge-homeassistant#1]
thats the json of one my thermostats:
thermostat.badezimmer_mode_9
{
  "max_temp": 35,
  "fan": "off",
 **"battery_level": 45,**
  "node_id": 9,
  "min_temp": 7,
  **"current_temperature": 25,**
  "target_temp_low": 21,
  **"temperature": 21,**
  "unit_of_measurement": "°C",
  **"current_operation": "Comfort",**
  "target_temp_high": 21,
  "friendly_name": "Bad Thermostat"
}
i would love to have the characteristics in *bold* avail. in homebridge.
i had them before with homebridge-zway.. but now i use openzwave to get it working with home-assistant.
`battery_level` and `current_operations `are optional for me, because i just use `temperature` to set the target temperature and `current_temperature` to know the current temperature in the room

**Comment by maddox** [comment]
:cool: 

I can attempt to do a quick first pass in making this work, but not actually having a thermostat is definitely going to make doing this complicated.

**Comment by luxus** [comment]
i would try my best to help you..
as far i remember there is a demo thermostat ? https://github.com/balloob/home-assistant/blob/dev/homeassistant/components/thermostat/demo.py

**Comment by maddox** [comment]
I can spin up a branch, but you're going to have to know how to use checked out versions of homebridge  plugins to test it. I can't publish it until it actually works. And I certainly can't publish it over and over to see if it works.

Someone could always just send me an Ecobee too, heh.

**Comment by luxus** [comment]
npm install <githubname>/<githubrepo>[#<commit-ish>] sounds not too complicated.

**Comment by maddox** [comment]
So, after taking a look at this, I've decided not to move forward with it. The primary reason is simple: I don't have a smart thermostat.

While I'd love for this plugin to support it, I just don't have time to devote to something that I can't actively test or get anything out of. Open source can be very self serving and that's definitely the case for this plugin. My apologies for things being like this, but I just don't have the time available to write something in the blind and that I'm not going to get anything out of. 

That being said, I absolutely welcome any contributions for this feature, thats actually the real beauty of open source :)

So, I'm going to just close this for now.

**Comment by luxus** [comment]
maybe now some more peoples are working on this.. we can reopen it @maddox ? perhaps someone else is willing to add climate to this plugin?
